import type { Config } from "tailwindcss";

const config: Config = {
  content: [
    "./components/**/*.{js,ts,jsx,tsx,mdx}",
    "./app/**/*.{js,ts,jsx,tsx,mdx}",
  ],
  theme: {
    colors: {
      "accent-1": "var(--accent-1)",
      "accent-2": "var(--accent-2)",
      "accent-3": "var(--accent-3)",
      "accent-4": "var(--accent-4)",
      "accent-5": "var(--accent-5)",
      "accent-6": "var(--accent-6)",
      "accent-7": "var(--accent-7)",
      "accent-8": "var(--accent-8)",
      "accent-9": "var(--accent-9)",
      "accent-10": "var(--accent-10)",
      "accent-11": "var(--accent-11)",
      "accent-12": "var(--accent-12)",
      "accent-a1": "var(--accent-a1)",
      "accent-a2": "var(--accent-a2)",
      "accent-a3": "var(--accent-a3)",
      "accent-a4": "var(--accent-a4)",
      "accent-a5": "var(--accent-a5)",
      "accent-a6": "var(--accent-a6)",
      "accent-a7": "var(--accent-a7)",
      "accent-a8": "var(--accent-a8)",
      "accent-a9": "var(--accent-a9)",
      "accent-a10": "var(--accent-a10)",
      "accent-a11": "var(--accent-a11)",
      "accent-a12": "var(--accent-a12)",
      "accent-contrast": "var(--accent-contrast)",
      "accent-surface": "var(--accent-surface)",
      "accent-indicator": "var(--accent-indicator)",
      "accent-track": "var(--accent-track)",
      "gray-1": "var(--gray-1)",
      "gray-2": "var(--gray-2)",
      "gray-3": "var(--gray-3)",
      "gray-4": "var(--gray-4)",
      "gray-5": "var(--gray-5)",
      "gray-6": "var(--gray-6)",
      "gray-7": "var(--gray-7)",
      "gray-8": "var(--gray-8)",
      "gray-9": "var(--gray-9)",
      "gray-10": "var(--gray-10)",
      "gray-11": "var(--gray-11)",
      "gray-12": "var(--gray-12)",
      "gray-a1": "var(--gray-a1)",
      "gray-a2": "var(--gray-a2)",
      "gray-a3": "var(--gray-a3)",
      "gray-a4": "var(--gray-a4)",
      "gray-a5": "var(--gray-a5)",
      "gray-a6": "var(--gray-a6)",
      "gray-a7": "var(--gray-a7)",
      "gray-a8": "var(--gray-a8)",
      "gray-a9": "var(--gray-a9)",
      "gray-a10": "var(--gray-a10)",
      "gray-a11": "var(--gray-a11)",
      "gray-a12": "var(--gray-a12)",
      "gray-contrast": "var(--gray-contrast)",
      "gray-surface": "var(--gray-surface)",
      "gray-indicator": "var(--gray-indicator)",
      "gray-track": "var(--gray-track)",
    },
    borderColor: {
      "card-classic": "var(--base-card-classic-border-color)",
      "card-classic-hover": "var(--base-card-classic-hover-border-color)",
      "card-classic-active": "var(--base-card-classic-active-border-color)",
    },
    boxShadow: {
      "1": "var(--shadow-1)",
      "2": "var(--shadow-2)",
      "3": "var(--shadow-3)",
      "4": "var(--shadow-4)",
      "5": "var(--shadow-5)",
      "6": "var(--shadow-6)",
      "card-surface": "var(--base-card-surface-box-shadow)",
      "card-surface-hover": "var(--base-card-surface-hover-box-shadow)",
      "card-surface-active": "var(--base-card-surface-active-box-shadow)",
    },
    extend: {
      backgroundImage: {
        "gradient-radial": "radial-gradient(var(--tw-gradient-stops))",
        "gradient-conic":
          "conic-gradient(from 180deg at 50% 50%, var(--tw-gradient-stops))",
      },
    },
  },
  plugins: [],
};
export default config;
