-- AlterTable
ALTER TABLE "Role" ALTER COLUMN "name" DROP NOT NULL,
ALTER COLUMN "createdAt" DROP NOT NULL,
ALTER COLUMN "updatedAt" DROP NOT NULL,
ALTER COLUMN "canEditShelter" DROP NOT NULL,
ALTER COLUMN "canEditAnimal" DROP NOT NULL,
ALTER COLUMN "canDeleteAnimal" DROP NOT NULL,
ALTER COLUMN "canCreateTask" DROP NOT NULL,
ALTER COLUMN "canEditTask" DROP NOT NULL,
ALTER COLUMN "canAssignTask" DROP NOT NULL,
ALTER COLUMN "canDeleteTask" DROP NOT NULL,
ALTER COLUMN "canCreateUser" DROP NOT NULL,
ALTER COLUMN "canEditUser" DROP NOT NULL,
ALTER COLUMN "canDeleteUser" DROP NOT NULL,
ALTER COLUMN "canAccessMedical" DROP NOT NULL,
ALTER COLUMN "canAccessBehavior" DROP NOT NULL,
ALTER COLUMN "canAccessAdoption" DROP NOT NULL;

-- AlterTable
-- ALTER TABLE "ShelterRoles" ALTER COLUMN "shelterId" DROP NOT NULL,
-- ALTER COLUMN "roleId" DROP NOT NULL,
-- ALTER COLUMN "createdAt" DROP NOT NULL,
-- ALTER COLUMN "updatedAt" DROP NOT NULL;

-- AlterTable
-- ALTER TABLE "ShelterUser" ALTER COLUMN "canAccessAdoption" DROP NOT NULL,
-- ALTER COLUMN "canAccessBehavior" DROP NOT NULL,
-- ALTER COLUMN "canAccessMedical" DROP NOT NULL,
-- ALTER COLUMN "canAssignTask" DROP NOT NULL,
-- ALTER COLUMN "canCreateTask" DROP NOT NULL,
-- ALTER COLUMN "canCreateUser" DROP NOT NULL,
-- ALTER COLUMN "canDeleteAnimal" DROP NOT NULL,
-- ALTER COLUMN "canDeleteTask" DROP NOT NULL,
-- ALTER COLUMN "canDeleteUser" DROP NOT NULL,
-- ALTER COLUMN "canEditAnimal" DROP NOT NULL,
-- ALTER COLUMN "canEditShelter" DROP NOT NULL,
-- ALTER COLUMN "canEditTask" DROP NOT NULL,
-- ALTER COLUMN "canEditUser" DROP NOT NULL,
-- ALTER COLUMN "roleId" DROP NOT NULL;

