import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "@radix-ui/themes/styles.css";
import { Flex, Theme } from "@radix-ui/themes";
import React from "react";
// import { AuthKitProvider } from "@workos-inc/authkit-nextjs";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    // {/* <AuthKitProvider> */}
    <Theme>
      <Flex direction="row">
        {/* <Sidebar /> */}
        <Flex
          overflowY={"scroll"}
          flexGrow={"1"}
          justify={"center"}
          direction="column"
        >
          {children}
        </Flex>
      </Flex>
      {/* <ThemePanel /> */}
    </Theme>
    // {/* </AuthKitProvider> */}
  );
}
